In [10]:
#1.Import the numpy package under the name np 

import numpy as np

In [11]:
#2.Create a null vector of size 10

vector1 = np.zeros(10)
vector1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#3. Create a null vector of size 10 but the fifth value which is 1 

vector2 = vector1
vector2[4] = 1
vector2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
#4. Create a vector with values ranging from 10 to 49

vector3 = np.arange(10,50)
vector3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
#5. Create a 3x3 matrix with values ranging from 0 to 8 

vector4 = np.arange(9).reshape(3,3)
vector4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#6.Find indices of non-zero elements from [1,2,0,0,4,0]

new_array = ([1,2,0,0,4,0])
for i in new_array:
    if i != 0:
        print(new_array.index(i))

0
1
4


In [19]:
#7. Create a 3x3 identity matrix

identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#8. Create a 3x3x3 array with random values

random_values = np.random.random((3,3,3))
random_values

array([[[0.31004601, 0.61605717, 0.67857178],
        [0.48066834, 0.32483558, 0.80462963],
        [0.51658845, 0.57786154, 0.46535143]],

       [[0.63515811, 0.33579135, 0.63296471],
        [0.11742326, 0.78222512, 0.26023531],
        [0.91065585, 0.72437192, 0.93022693]],

       [[0.91333406, 0.15492319, 0.31236692],
        [0.36237229, 0.73296114, 0.17453776],
        [0.12546441, 0.03608137, 0.00105354]]])

In [25]:
#9. Create a 10x10 array with random values and find the minimum and maximum values

random_values2 = np.random.random((10,10))
random_values2

array([[0.29097312, 0.18958637, 0.58177538, 0.25546211, 0.65113038,
        0.84738775, 0.03135678, 0.94281242, 0.62021372, 0.41589611],
       [0.39789109, 0.73300989, 0.2369393 , 0.82940545, 0.23840101,
        0.25153578, 0.02613858, 0.63396388, 0.2621829 , 0.6225687 ],
       [0.82412521, 0.08406454, 0.19925754, 0.18380642, 0.8015549 ,
        0.18680587, 0.5350663 , 0.0309446 , 0.64847274, 0.93838247],
       [0.91816372, 0.95873496, 0.21004186, 0.81004941, 0.6688154 ,
        0.79664788, 0.09862167, 0.11583597, 0.25818632, 0.85061   ],
       [0.4993047 , 0.35756369, 0.08433278, 0.86777997, 0.7942008 ,
        0.57558815, 0.86057671, 0.97139116, 0.68633741, 0.34491292],
       [0.03914574, 0.79523027, 0.47074102, 0.12673653, 0.89711847,
        0.72063148, 0.7713888 , 0.60744167, 0.98177707, 0.98608085],
       [0.15302498, 0.1362075 , 0.19546433, 0.11677422, 0.20535027,
        0.5807364 , 0.61346532, 0.96344599, 0.67574324, 0.99822096],
       [0.48351421, 0.33508904, 0.5753095

In [30]:
print(np.min(random_values2))
print(np.max(random_values2))

0.01634532035231373
0.9982209598477375


In [33]:
#10. Create a random vector of size 30 and find the mean value

random_vector = np.random.random(30)
print(random_vector)

[0.55193401 0.8078737  0.88467956 0.36172652 0.04892357 0.69183521
 0.0803303  0.18707899 0.46037124 0.48032012 0.32660563 0.59158575
 0.80387901 0.47119662 0.68099579 0.10290305 0.82708323 0.41465783
 0.50186368 0.5027737  0.58246425 0.92363678 0.31977972 0.00565939
 0.01034529 0.80932967 0.91290961 0.15618328 0.01000487 0.56890773]


In [34]:
np.mean(random_vector)

0.4692612699060651

In [36]:
#11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

diagonal = np.diag([0,1,2,3,4])
diagonal

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [81]:
#12. Normalize a 5x5 random matrix 

Mat = np.random.randint(100, size=25).reshape(5,5)
Mat

array([[54, 43, 65, 58, 54],
       [79, 70, 51, 90, 67],
       [68, 77, 58, 21, 20],
       [82, 21, 55, 44, 30],
       [63,  2, 67, 83,  8]])

In [83]:
from sklearn.preprocessing import normalize

Mat_normed = normalize(Mat, axis=1, norm='l1')
Mat_normed

array([[0.19708029, 0.15693431, 0.23722628, 0.21167883, 0.19708029],
       [0.22128852, 0.19607843, 0.14285714, 0.25210084, 0.18767507],
       [0.27868852, 0.31557377, 0.23770492, 0.08606557, 0.08196721],
       [0.35344828, 0.09051724, 0.23706897, 0.18965517, 0.12931034],
       [0.28251121, 0.00896861, 0.30044843, 0.37219731, 0.03587444]])

In [48]:
#13. How to find common values between two arrays? 

array1 = [(1,2,3,4,5)]
array2 = [(4,5,6,7,8)]

np.intersect1d(array1, array2)

array([4, 5])

In [54]:
#14. Create a random vector of size 10 and sort it 

ran_vector = np.random.random(10)
ran_vector


array([0.97597089, 0.62907376, 0.09390543, 0.82358526, 0.70643103,
       0.48887751, 0.97775827, 0.71757946, 0.37770992, 0.03665702])

In [55]:
np.sort(ran_vector)

array([0.03665702, 0.09390543, 0.37770992, 0.48887751, 0.62907376,
       0.70643103, 0.71757946, 0.82358526, 0.97597089, 0.97775827])

In [56]:
#15. Create random vector of size 10 and replace the maximum value by 0

ran_vector2 = np.random.random(10)
ran_vector2

array([0.70806265, 0.20276996, 0.34202811, 0.41083253, 0.0384279 ,
       0.64424928, 0.7049226 , 0.35549752, 0.33070333, 0.3839341 ])

In [63]:
ran_vector2 = np.sort(ran_vector2)
ran_vector2

array([0.0384279 , 0.20276996, 0.33070333, 0.34202811, 0.35549752,
       0.3839341 , 0.41083253, 0.64424928, 0.7049226 , 0.70806265])

In [62]:
np.delete(ran_vector2, [-1])

array([0.0384279 , 0.20276996, 0.33070333, 0.34202811, 0.35549752,
       0.3839341 , 0.41083253, 0.64424928, 0.7049226 ])

In [64]:
#16. Subtract the mean of each row of a matrix 

matrix1 = np.random.rand(3,2)
matrix1

array([[0.27367978, 0.81714884],
       [0.38954989, 0.49174171],
       [0.11877305, 0.75437784]])

In [66]:
matrix1 = matrix1 - matrix1.mean(axis=1, keepdims=True)

matrix1


array([[-0.27173453,  0.27173453],
       [-0.05109591,  0.05109591],
       [-0.31780239,  0.31780239]])

In [77]:
#17. How to get the n largest values of an array
#Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

Z = np.arange(10000)
np.random.shuffle(Z)
Z

n = 5

print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


In [70]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

random_again = np.random.randint(10, size=15).reshape(5,3)
random_again

array([[8, 3, 5],
       [9, 8, 6],
       [6, 6, 4],
       [2, 6, 1],
       [0, 9, 1]])

In [73]:
np.where(random_again > 4, random_again*random_again, random_again)

array([[64,  3, 25],
       [81, 64, 36],
       [36, 36,  4],
       [ 2, 36,  1],
       [ 0, 81,  1]])